code --install-extension Angular.ng-template
code --install-extension christian-kohler.npm-intellisense
code --install-extension cyrilletuzi.angular-schematics
code --install-extension dbaeumer.jshint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension formulahendry.dotnet
code --install-extension formulahendry.dotnet-test-explorer
code --install-extension HookyQR.beautify
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension Leopotam.csharpfixformat
code --install-extension Mikael.Angular-BeastCode
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension VisualStudioExptTeam.vscodeintellicode